title: Deyu's Yard 
description: 简约而不简单 
url: http://xudeyu.github.io
author: 
  name: Deyu 
  email: xvdeyu@gmail.com 
logo: assets/img/favicon.png
keywords: 
##  - Web
##  - HTML
##  - CSS
##  - JavaScript
##  - C++
##  - Linux
##  - Bash
##  - Vim

permalink: /:year/:month/:day/:title.html
paginate: 7
paginate_path: "page:num"
markdown: kramdown
markdown_ext:  md
excerpt_separator: "<!--more-->"
highlighter: rouge
lsi: false
exclude: ['README.md', '.*', 'bin/', 'Gemfile', 'node_modules', '*.log', 'package.json']
kramdown:
  input: GFM
  hard_wrap: false

ga: 'UA-106166580-1'
adsense:
disqus: 'xudeyu'
twitter:
  username: xvdeyu 

sass:
    style: compressed

defaults:
  -
    scope:
      path: "_drafts"
    values:
      layout: "blog"
  -
    scope:
      path: "_posts"
    values:
      layout: "blog"

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
